

//@version=5
indicator("STDDEV & ATR Gap")

period = input(20, "period")

atr = ta.atr(period)
stddev = ta.stdev(close, period)

stddev_atr_gap = stddev - atr

color volatile = input.color(color.red, "volatile")
color ranging = input.color(color.gray, "ranging")
color color_swap = stddev_atr_gap > 0.0 ? volatile : ranging

plot(stddev_atr_gap, "stddev_atr_gap", color_swap, 3, plot.style_histogram)
hline(0, 'base_line', color.white)
