indicator("VHF_improve")

//Apperantly,this indicator has a significant flaw that the vhf value is high even the price is ranging.
//to fix this issue, simply, just chage the period of the denominator.

p = input(10, "p")
p2=p*3



hp=ta.highest(close,p)
lp=ta.lowest(close,p)


numerator=math.abs(hp-lp)

source=math.abs(close-close[1])
denominator=math.sum(source,p2)

vhf=(numerator/denominator)*100
hline(20, 'VHF Level', color.white)
plot(vhf,"p",color.red)
