//@version=5

indicator("Aroon[Rsi-Adjusted]-Net")

rolling_p = input(20, 'rolling period')
level = input(90, 'level')

upper_level = level
lower_level = -level

RSI = ta.rsi(close, rolling_p)

Aroon_Up = 100 * (ta.highestbars(close, rolling_p+1) + rolling_p)/rolling_p
Aroon_Down = 100 * (ta.lowestbars(close, rolling_p+1) + rolling_p)/rolling_p

Aroon_Up_RSI = 100 * (ta.highestbars(RSI, rolling_p+1) + rolling_p)/rolling_p
Aroon_Down_RSI = 100 * (ta.lowestbars(RSI, rolling_p+1) + rolling_p)/rolling_p

upper_spread = Aroon_Up - Aroon_Up_RSI
lower_spread = Aroon_Down - Aroon_Down_RSI

net_arn =  math.abs(upper_spread) - math.abs(lower_spread)

plot(upper_spread, "upper_spread",color.red, 1, plot.style_histogram)
plot(lower_spread, "lower_spread",color.green, 1, plot.style_histogram)

plot(net_arn, "net_arn",color.yellow)
hline(0, '0', color.white)

hline(upper_level, 'upper_level', color.white)
hline(lower_level, 'lower_level', color.white)
